name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Java セットアップ
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Spring Boot アプリのビルド
        working-directory: backend/demo
        run: ./mvnw package -DskipTests
      
      - name: JARファイルの存在確認
        run: ls -lh backend/demo/target/

      - name: EC2 に JAR を転送
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: backend/demo/target/demo-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/app/

      - name: EC2 でアプリを起動
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/app/*.jar > app.log 2>&1 &
            
      
