name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Java セットアップ
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

<<<<<<< HEAD
      - name: ルートディレクトリ確認
        run: ls -lh

      - name: Spring Boot アプリのビルド
        run: mvn -f "Documents/研修/my-inventory-app/backend/demo/pom.xml" package -DskipTests

      - name: JARファイルの存在確認
        run: ls -lh "Documents/研修/my-inventory-app/backend/demo/target/"
=======
      - name: Spring Boot アプリのビルド
        working-directory: backend/demo
        run: ./mvnw package -DskipTests
      
      - name: JARファイルの存在確認
        run: ls -lh backend/demo/target/
>>>>>>> 7a3af1a (fix: set correct Git root)

      - name: EC2 に JAR を転送
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
<<<<<<< HEAD
          source: "Documents/研修/my-inventory-app/backend/demo/target/demo-0.0.1-SNAPSHOT.jar"
=======
          source: backend/demo/target/demo-0.0.1-SNAPSHOT.jar
>>>>>>> 7a3af1a (fix: set correct Git root)
          target: /home/ec2-user/app/

      - name: EC2 でアプリを起動
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
<<<<<<< HEAD
            echo "==== Java 確認 ===="
            java -version || echo "Javaが見つかりません"
            
            echo "==== ファイル確認 ===="
            ls -lh /home/ec2-user/app/
            
            echo "==== アプリ起動 ===="
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/app/demo-0.0.1-SNAPSHOT.jar > /home/ec2-user/app/app.log 2>&1 &
=======
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/app/*.jar > app.log 2>&1 &
            
      
>>>>>>> 7a3af1a (fix: set correct Git root)
